CREATE TABLE IF NOT EXISTS overtime (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    hours SMALLINT DEFAULT 0,
    minutes SMALLINT DEFAULT 0,
    message VARCHAR(150)
);